#!/bin/bash

# Ask for confirmation before pushing to main or master branch.
# NOTE: this only affects repositories initialized after acuiring this script.

protected_branches=('master' 'main')
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ " ${protected_branches[*]} " =~ " ${current_branch} " ]]; then
  read -p "You're about to push $current_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
  echo
  
  if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
      exit 0 # push will execute
  fi
  
  exit 1 # push will not execute
fi

exit 0 # push will execute

